config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  
  get '/about', to: 'static_pages#about'
  get '/cats_with_captions', to: 'static_pages#cats_with_captions'
  get '/cats_without_captions', to: 'static_pages#cats_without_captions'
  get '/essays', to: 'static_pages#essays'
  get '/index', to: 'static_pages#index'
  get '/quotes', to: 'static_pages#quotes'
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    
  end
  
  def cats_with_captions
    
  end
  
  def cats_without_captions
    
  end

  def essays
    
  end

  def quotes
    
  end
  
  def about
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="container">
  <div class="row">
    <div class="col-sm-6 well left">
      <p>
        This is where the tagline for our organization would be if we were not too lazy to think of one.
      </p>
      <div><%= link_to "About Us", about_path %></div>
    </div>
    <div class="col-sm-6 well right">
      <h4>Links</h4>
      <div><%= link_to "Quotes", quotes_path %></div>
      <div><%= link_to "Essays", essays_path %></div>
      <div><%= link_to "Cats with Captions", cats_with_captions_path %></div>
      <div><%= link_to "Cats without Captions", cats_without_captions_path %></div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-header">
    <%= link_to "ICS 616 Demo", root_path, class: "navbar-brand" %>
  </div>
  <ul class="nav navbar-nav">
    <li><%= link_to "Quotes", quotes_path %></li>
    <li><%= link_to "Essays", essays_path %></li>
    <li><%= link_to "Cats with Captions", cats_with_captions_path %></li>
    <li><%= link_to "Cats without Captions", cats_without_captions_path %></li>
    <li><%= link_to "About", about_path %></li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/static_pages/about.html.erb
<div class="container">
  <div class="well">
    <h1>
      About
    </h1>
    This site was created as a demo for ICS 616 in Fall 2015, first for usability and then as an
    example of how to use the Cucumber testing framework.
  </div>
</div>

app/views/static_pages/cats_captions.html.erb
<% provide(:title, "ICS 616 Demo - Cats with Captions") %>

<div class="container">
  <div class="well">
    <h1>
      Cats with Captions
      <small>A while back</small>
    </h1>
    <div class="row">
      <div class="col-sm-6">
        <%= image_tag "cat-and-computer-saving-the-world.jpg",
                      class: "img-responsive img-thumbnail center-block" %>
      </div>
      <div class="col-sm-6">
        <%= image_tag "funny-pictures-cat-fixes-your-computer.jpg",
                      class: "img-responsive img-thumbnail center-block" %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-6">
        <%= image_tag "funny-pictures-cat-is-on-line.jpg",
                      class: "img-responsive img-thumbnail center-block" %>
      </div>
      <div class="col-sm-6">
        <%= image_tag "funny-pictures-cat-is-sleeping-on-the-computer-monitor-as-per-instructions.jpg", 
                      class: "img-responsive img-thumbnail center-block" %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-6">
        <%= image_tag "funny-pictures-cat-sleeps.jpg", 
                      class: "img-responsive img-thumbnail center-block" %>
      </div>
      <div class="col-sm-6">
        <%= image_tag "funny-pictures-your-cat-is-over-stimulated.jpg", 
                      class: "img-responsive img-thumbnail center-block" %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-6">
        <%= image_tag "lieutenant-dan-you-got-new-legs.jpg", 
                      class: "img-responsive img-thumbnail center-block" %>
      </div>
      <div class="col-sm-6">
        <%= image_tag "pick_me_kitten.jpeg", 
                      class: "img-responsive img-thumbnail center-block" %>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/cats_with_captions.html.erb
<% provide(:title, "ICS 616 Demo - Cats with Captions") %>

<div class="container">
  <div class="well">
    <h1>
      Cats with Captions
    </h1>
    <div class="row">
      <div class="col-sm-6">
        <%= image_tag "cat-and-computer-saving-the-world.jpg",
                      class: "img-responsive img-thumbnail center-block" %>
      </div>
      <div class="col-sm-6">
        <%= image_tag "funny-pictures-cat-fixes-your-computer.jpg",
                      class: "img-responsive img-thumbnail center-block" %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-6">
        <%= image_tag "funny-pictures-cat-is-on-line.jpg",
                      class: "img-responsive img-thumbnail center-block" %>
      </div>
      <div class="col-sm-6">
        <%= image_tag "funny-pictures-cat-is-sleeping-on-the-computer-monitor-as-per-instructions.jpg", 
                      class: "img-responsive img-thumbnail center-block" %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-6">
        <%= image_tag "funny-pictures-cat-sleeps.jpg", 
                      class: "img-responsive img-thumbnail center-block" %>
      </div>
      <div class="col-sm-6">
        <%= image_tag "funny-pictures-your-cat-is-over-stimulated.jpg", 
                      class: "img-responsive img-thumbnail center-block" %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-6">
        <%= image_tag "lieutenant-dan-you-got-new-legs.jpg", 
                      class: "img-responsive img-thumbnail center-block" %>
      </div>
      <div class="col-sm-6">
        <%= image_tag "pick_me_kitten.jpeg", 
                      class: "img-responsive img-thumbnail center-block" %>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/cats_without_captions.html.erb
<% provide(:title, "ICS 616 Demo - Cats with Captions") %>

<div class="container">
  <div class="well">
    <h1>
      Cats without Captions
    </h1>
    <div class="row">
      <div class="col-sm-6">
        <%= image_tag "Adorable-kitties-kitties 1.jpg",
                      class: "img-responsive img-thumbnail center-block" %>
      </div>
      <div class="col-sm-6">
        <%= image_tag "11591714654_f147615d47_b.jpg",
                      class: "img-responsive img-thumbnail center-block" %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-6">
        <%= image_tag "9036284474_a118cb65fa_z.jpg",
                      class: "img-responsive img-thumbnail center-block" %>
      </div>
      <div class="col-sm-6">
        <%= image_tag "8960576518_a65557d1c2_z.jpg", 
                      class: "img-responsive img-thumbnail center-block" %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-6">
        <%= image_tag "8707301033_3c8a89363e_o.jpg",
                     class: "img-responsive img-thumbnail center-block" %>
      </div>
      <div class="col-sm-6">
        <%= image_tag "8510686043_e8dd2f541f_b.jpg",
                     class: "img-responsive img-thumbnail center-block" %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-6">
        <%= image_tag "20121122-205627.jpg", 
                      class: "img-responsive img-thumbnail center-block" %>
      </div>
      <div class="col-sm-6">
        <%= image_tag "295530_260301370771513_998656246_n.jpg",
                      class: "img-responsive img-thumbnail center-block" %>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/essays.html.erb
<% provide(:title, "ICS 616 Demo - Essays") %>

<div class="container">
  <div class="well">
    <h1>
      Essays
    </h1>
    <h3>
      Very Like a Whale
      <small>by Ogden Nash</small>
    </h3>

    <p>        
    One thing that literature would be greatly the better for<br />
    Would be a more restricted employment by the authors of simile and metaphor.
    </p>
    <p>
    Authors of all races, be they Greeks, Romans, Teutons or Celts,<br />
    Can't seem just to say that anything is the thing it is but have to go out of their way to say that it is like something else.
    </p>
    <p>
    What does it mean when we are told<br />
    That that Assyrian came down like a wolf on the fold?
    </p>
    <p>
    In the first place, George Gordon Byron had enough experience<br />
    To know that it probably wasn't just one Assyrian, it was a lot of Assyrians.
    </p>
    <p>
    However, as too many arguments are apt to induce apoplexy and thus hinder longevity.<br />
    We'll let it pass as one Assyrian for the sake of brevity.
    </p>
    <p>
    Now then, this particular Assyrian, the one whose cohorts were gleaming in purple and gold,<br />
    Just what does the poet mean when he says he came down like a wolf on the fold?
    </p>
    <p>
    In heaven and earth more than is dreamed of in our philosophy there are great many things.<br />
    But I don't imagine that among them there is a wolf with purple and gold cohorts or purple and gold anythings.
    </p>
    <p>
    No, no, Lord Byron, before I'll believe that this Assyrian was actually like a wolf I must have some kind of proof;<br />
    Did he run on all fours and did he have a hairy tail and a big red mouth and big white teeth and did he say Woof Woof?
    </p>
    <p>
    Frankly I think it is very unlikely, and all you were entitled to say, at the very most,<br />
    Was that the Assyrian cohorts came down like a lot of Assyrian cohorts about to destroy the Hebrew host.
    </p>
    <p>
    But that wasn't fancy enough for Lord Byron, oh dear me no, he had to invent a lot of figures of speech and then interpolate them,<br />
    With the result that whenever you mention Old Testament soldiers to people they say Oh yes, they're the ones that a lot of wolves dressed up in gold and purple ate them.
    </p>
    <p>
    That's the kind of thing that's being done all the time by poets, from Homer to Tennyson;<br />
    They're always comparing ladies to lilies and veal to venison,
    </p>
    <p>
    And they always say things like that the snow is a white blanket after a winter storm.<br />
    Oh it is, is it, all right then, you sleep under a six-inch blanket of snow and I'll sleep under a half-inch blanket of unpoetical blanket material and we'll see which one keeps warm,
    </p>
    <p>
    And after that maybe you'll begin to comprehend dimly<br />
    What I mean by too much metaphor and simile.        
    </p>
  </div>
</div>

app/views/static_pages/index.html.erb
<% provide(:title, "ICS 616 Demo") %>

<div class="container">
  <div class="well">
    <h1>
      Home
    </h1>
    This is sample text.<br />
    However, it is very difficult for me to generate large amounts of sample text.<br />
    Therefore, the rest of the text on this home page is from <a href="http://puzzling.stackexchange.com/questions/15097/who-shall-come-to-the-tea-party">here</a>.
    <br />
    
    <h2>Who shall come to the tea party?</h2>
    <p>All of your stuffed animals are assembled, anxiously waiting to learn who will be be invited as the Guest of Honor to your next tea party.  </p>

    <p>This is to be an exclusive party, after all, as there is to be only <em>one</em> Guest of Honor.  This is by necessity, because you have only two strawberry pastries, and you obviously intend to eat one of those yourself. (Cook was most annoyed with you for taking so many infinite bags of pastries yesterday, and has since cut off your supply).  All the other guests at the tea party shall only receive tea.</p>

    <p>So now you must decide which of your many guests will be the Guest of Honor, who receives the coveted strawberry pastry.</p>

    <p>Your first instinct, of course, is to invite the valiant Mr. Bun to be the Guest of Honor.  After all, he's brave and noble and always tells the truth.  But then you think of poor insidious Duke Froggington II, who admittedly is dastardly and always lies, but in your heart you know that these character flaws are only due to his tragic childhood.  You see, the perfidious Duke Froggington II grew up all alone in a dank 30-meter well, trying to leap his way to light and freedom.  You know what that's like, and your heart aches for him.  And there are similar reasons why you might choose almost any of the six dozen other stuffed animals that pack every available surface in your bedroom.</p>

    <p>No, you find that you're completely unable to decide which stuffed animal should be the Guest of Honor at your tea party, and so you instead devise a game for the stuffed animals to play, to determine the Guest of Honor fairly.</p>

    <p>The game works in this way:</p>

    <p>First, you choose Mr. Bun as the initial nominee as Guest of Honor.  He's the obvious first candidate, as the noblest of all your stuffed animals.</p>

    <p>Then, starting with the nefarious Duke Froggington II and descending through the other stuffed animals in order of seniority and ending with Peanut (an ugly mouse given to you by your annoying older sister at your last birthday fête, and usually tucked far back in your dresser behind your latin coursebooks), each stuffed animal still in attendance is asked if they wish to declare themselves to be the new nominee as Guest of Honor.  If they do, then they become the new nominee, and the previous nominee is returned to the toy chest, where they must remain until after the tea party.</p>

    <p>Whenever the nominee changes, the whole process starts again;  Every animal (in order of seniority, and starting with the most senior remaining animal) is given a fresh opportunity to nominate themselves, even if they had previously chosen not to.  As before, if an animal chooses to nominate themselves, the current nominee is returned to the toy chest, and may not attend the tea party.</p>

    <p>This process continues until no further stuffed animals wish to declare themselves as the nominee.</p>

    <p>Once no more stuffed animals wish to make themselves the nominee, whoever remains as the nominee shall become the Guest of Honor and will receive a strawberry pastry at the tea party.  The other remaining stuffed animals shall receive tea.  Any stuffed animals in the toy chest get nothing. (At least, not until they're brought out again for the next tea party (which will likely be in ten minutes or so))</p>

    <p>A few obvious points which you know instinctively are:</p>

    <ul>
    <li>All stuffed animals <em>love</em> strawberry pastries (as does everyone of refinement and distinction.  Peanut would probably love strawberry pastries too, despite having neither refinement nor distinction, though you've certainly never wasted one on her, even yesterday when you had several infinite supplies of them).  This means that each stuffed animal dearly wishes to be the Guest of Honor.</li>
    <li>All stuffed animals like tea, so none of them wish to completely miss the party by being put back into the toy chest.</li>
    <li>All stuffed animals are perfect logicians (I mean, obviously.  Do I even need to mention this?)</li>
    <li>Stuffed animals don't hold grudges against one another;  they will remain fast friends even if one sends another to the toy chest.  On the contrary, they will recognise that it was the only logical thing to do, and will probably laugh about it at your next tea party, later this afternoon.</li>
    <li>While the treacherous Duke Froggington II always lies, you've long since adapted to that, and aren't ever confused any more about what he means when he tells you which door leads to certain doom and which leads to your afternoon Latin classes (though you're still not convinced that there's actually much of a difference between the two).  Similarly, there will be no confusion on your part about whether or not he wishes to become the new nominee, regardless of what lies he might say.</li>
    <li>For the sake of clarity, you have six dozen and two stuffed animals in total.  With Mr. Bun as your favourite, the despicable Duke Froggington II as your second favourite, and Peanut as your least favourite.  Other stuffed animals may be identified by number, with the next animal after the treacherous Duke Froggington II being number 3.</li>
    </ul>

    <p><strong>Of your stuffed animals, how many will attend your tea party, and which will be the Guest of Honor?</strong></p>        
  </div>
</div>

app/views/static_pages/quotes.html.erb
<% provide(:title, "ICS 616 Demo - Quotes") %>

<div class="container">
  <div class="well">
    <h1>
      Quotes
    </h1>
    <ul>
      <li>Help stamp out and abolish redundancy!</li>
      <li>A closed mouth gathers no feet.</li>
      <li>Schizophrenia beats being alone.</li>
      <li>After all is said and done, usually more is said than done.</li>
      <li>If rabbits' feet are so lucky, what happened to the rabbit?</li>
      <li>Be alert!  We need more lerts.</li>
      <li>Time is just nature's way of keeping everything from happening at once.</li>
      <li>I'm all for computer dating, but I wouldn't want one to marry my sister.</li>
      <li>Time flies like an arrow.  However, fruit flies like bananas.</li>
      <li>Reality is for people who can't face science fiction.</li>
      <li>No problem is so formidable that you can't just run away from it.</li>
      <li>While money can't buy you happiness, it certainly lets you choose your own form of misery.</li>
      <li>You can fool some people all of the time, and you can fool all people some of the time, but you can make a fool of yourself anytime.</li>
      <li>Never stand between a fire hydrant and a dog.</li>
      <li>Remember, the fact that you're paranoid doesn't mean that they're NOT out to get you!</li>
      <li>Eschew Obfuscation!</li>
      <li>Atlas Shrugged starts with the line, "Who is John Galt?"  By the end of the novel, the reader has a different question: "When will John Galt shut up?" </li>
      <li>There are 10 types of people in this world: those who know binary and those who do not.</li>
      <li>There are 3 types of people in this world: those who can count and those who cannot.  </li>
      <li>There are three ways to know that you are getting old.  First, there is the loss of memory.  Second... darn it, I can't remember the other two.</li>
      <li>A juvenile delinquent is someone who plays his Saxophone too loud.</li>
      <li>The average Saxophonist is egotistical enough to believe that he can play a duet by himself.</li>
      <li>Why couldn't our Founding Fathers have fought for representation without taxation?</li>
      <li>Freedom of speech is the right to talk about issues that you do not understand.</li>
      <li>It is very difficult to teach children the alphabet these days.  They all think that "V" comes right after "T."</li>
      <li>Look on the bright side!  Whenever a car is stolen, a new parking space opens up!</li>
      <li>In America, people drive on the right side of the road.  In England, people drive on the left side of the road.  In Hawaii, people drive in the shade.</li>
      <li>Bigamy is having one spouse too many.  Monogamy is sometimes the same.</li>
      <li>I have nothing against political jokes.  I just wonder how they ever got elected.</li>
      <li>An election year is a period when the Republicans and Democrats devote their time to saving the country from each other. </li>
      <li>An election is a system where We the People decide which politicians we want to screw up the nation for us.</li>
      <li>Having four years between elections is a good thing.  It takes us that long to regain our faith in the system.</li>
      <li>If our politicians are so concerned about human suffering, they should look at the average American taxpayer.</li>
      <li>Darwin proposed that humans came from apes.  Politicians prove that it could go either way.</li>
      <li>Diplomacy is the art of saying "Nice doggy, nice doggy" until you can find a stick.</li>
      <li>Don't be unhappy if your dreams never come true--be thankful that your nightmares don't. </li>
      <li>The average college student can walk past the local YMCA and think that they spelled Macy's wrong.</li>
      <li>Statisticians collect facts, then draw their own confusions.</li>
      <li>Why will tourists travel thousands of miles away from anyone they know, and then send back cards saying "Wish you were here?"</li>
    </ul>
  </div>
</div>